version: '2'
services:
    postgres:
        image: postgres:9.6.2
        environment:
            - "POSTGRES_PASSWORD=${B2SHARE_POSTGRESQL_PASSWORD}"
            - "POSTGRES_USER=${B2SHARE_POSTGRESQL_USER}"
            - "PGDATA=/var/lib/postgresql/data"
        volumes:
            - "${B2SHARE_DATADIR}/postgres-data:/var/lib/postgresql/data"
        expose:
            - "5432"

    b2share:
        image: eudatb2share/b2share:2.0.1
        environment:
            - "B2ACCESS_CONSUMER_KEY=${B2ACCESS_CONSUMER_KEY}"
            - "B2ACCESS_SECRET_KEY=${B2ACCESS_SECRET_KEY}"
            - "USE_STAGING_B2ACCESS=${USE_STAGING_B2ACCESS}"
            - "B2SHARE_SECRET_KEY=${B2SHARE_SECRET_KEY}"
            - "B2SHARE_JSONSCHEMAS_HOST=${B2SHARE_JSONSCHEMAS_HOST}"
            - "INIT_DB_AND_INDEX=${INIT_DB_AND_INDEX}"
            - "LOAD_DEMO_COMMUNITIES_AND_RECORDS=${LOAD_DEMO_COMMUNITIES_AND_RECORDS}"
            - "B2SHARE_PREFERRED_URL_SCHEME=https"
            - "B2SHARE_SQLALCHEMY_DATABASE_URI='postgresql+psycopg2://${B2SHARE_POSTGRESQL_USER}:${B2SHARE_POSTGRESQL_PASSWORD}@postgres:5432/${B2SHARE_POSTGRESQL_DBNAME}'"
            - "B2SHARE_CACHE_REDIS_HOST='redis'"
            - "B2SHARE_CACHE_REDIS_URL='redis://redis:6379/0'"
            - "B2SHARE_ACCOUNTS_SESSION_REDIS_URL='redis://redis:6379/1'"
            - "B2SHARE_BROKER_URL='amqp://${B2SHARE_RABBITMQ_USER}:${B2SHARE_RABBITMQ_PASS}@mq:5672/'"
            - "B2SHARE_CELERY_RESULT_BACKEND='redis://redis:6379/2'"
            - "B2SHARE_SEARCH_ELASTIC_HOSTS='elasticsearch'"
        volumes:
            - "${B2SHARE_DATADIR}/b2share-data:/usr/var/b2share-instance"
        expose:
            - "5000"
        links:
            - elasticsearch
            - redis
            - postgres

    elasticsearch:
        build: elasticsearch
        expose:
            - "9200"
            - "9300"
        volumes:
            - "${B2SHARE_DATADIR}/elasticsearch-data:/usr/share/elasticsearch/data"

    redis:
        image: redis:3.2-alpine
        expose:
            - "6379"
        volumes:
            - "${B2SHARE_DATADIR}/redis-data:/data"

    nginx:
        build: nginx
        ports:
            - "80:80"
            - "443:443"
        # volumes:
        #     - "${B2SHARE_DATADIR}/nginx-data/ssl:/etc/ssl/"
        links:
            - b2share

    mq:
        hostname: b2share-redis
        image: rabbitmq:3.6-management-alpine
        restart: "always"
        environment:
            - "RABBITMQ_DEFAULT_USER=${B2SHARE_RABBITMQ_USER}"
            - "RABBITMQ_DEFAULT_PASS=${B2SHARE_RABBITMQ_PASS}"
        expose:
            - "15672"
            - "5672"
        volumes:
            - "${B2SHARE_DATADIR}/rabbitmq-data:/var/lib/rabbitmq"
